"""empty message

Revision ID: 4e10eaa84dc0
Revises: d0f3347c5339
Create Date: 2021-01-05 10:21:04.483774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e10eaa84dc0'
down_revision = 'd0f3347c5339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('check_alembic', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'check_alembic')
    # ### end Alembic commands ###
