"""empty message

Revision ID: 9139158c0b0d
Revises: 4e10eaa84dc0
Create Date: 2021-01-05 10:23:53.175778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9139158c0b0d'
down_revision = '4e10eaa84dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'check_alembic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('check_alembic', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
