"""empty message

Revision ID: fdd3e75c1ac6
Revises: 9139158c0b0d
Create Date: 2021-01-05 10:41:27.663665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd3e75c1ac6'
down_revision = '9139158c0b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('check_alembic', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'check_alembic')
    # ### end Alembic commands ###
